services:
  authorization.core:
    image: authorization.core
    build:
      context: .
      dockerfile: Authorization.Core/Dockerfile
  authorization.database: 
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authorization
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata: {}